# Generated by Django 5.2 on 2025-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAcoes',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('data_pregao', models.DateField()),
                ('preco_max', models.FloatField()),
                ('preco_min', models.FloatField()),
                ('preco_abertura', models.FloatField()),
                ('preco_fechamento', models.FloatField()),
                ('vol_negocios', models.BigIntegerField()),
                ('sigla_acao', models.CharField(max_length=10)),
                ('dividendos', models.FloatField(blank=True, null=True)),
                ('desdobramento', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
