# Generated by Django 5.2 on 2025-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('data_pregao', models.DateField()),
                ('preco_max', models.DecimalField(decimal_places=6, max_digits=10)),
                ('preco_min', models.DecimalField(decimal_places=6, max_digits=10)),
                ('preco_abertura', models.DecimalField(decimal_places=6, max_digits=10)),
                ('preco_fechamento', models.DecimalField(decimal_places=6, max_digits=10)),
                ('vol_negocios', models.IntegerField()),
                ('preco_fechamento_ajustado', models.DecimalField(decimal_places=6, max_digits=10)),
                ('sigla_acao', models.CharField(max_length=10)),
            ],
        ),
    ]
