# Generated by Django 5.2 on 2025-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAcoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.BigIntegerField()),
                ('data_pregao', models.DateField()),
                ('preco_max', models.FloatField()),
                ('preco_min', models.FloatField()),
                ('preco_abertura', models.FloatField()),
                ('preco_fechamento', models.FloatField()),
                ('vol_negocios', models.BigIntegerField()),
                ('sigla_acao', models.CharField(max_length=10)),
                ('dividendos', models.FloatField(blank=True, null=True)),
                ('desdobramento', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dados_acoes',
                'indexes': [models.Index(fields=['data_pregao', 'sigla_acao'], name='dados_acoes_data_pr_0459de_idx')],
            },
        ),
    ]
